### ISSUE TITLE
Issues during runtime

### ISSUE THREAD

**Issue by matthew-corbett** [keijiro/UltraFaceBarracuda#2] opened 2022-08-22 19:30 UTC
First, thank you for doing this.  It was immensely helpful to see how to use the texture rendering chain to parse the outputs of UltraFace.  I have a version of your work running, but I have  modified it to work during runtime on a HoloLens 2, using MIcrosoft's MediaCapture APIs to capture the RGB camera fames from the front of the HL2.  From these frame, I create a SoftwareBitmap and convert to a Unity Texture for use as an input into your rendering chain.  When I do this, the model returns 0 faces, for reasons I cannot understand. Can you think of a way around this?

The code Looks something like this:

public async Task<DetectedFaces> EvaluateVideoFrameAsync(byte[] bitmapFrame)
    {
        DetectedFaces result = new DetectedFaces();
        try
        {
            Texture2D imageMediaTexture = new Texture2D(320, 240, TextureFormat.RGB24, false);
            imageMediaTexture.LoadRawTextureData(bitmapFrame);
            imageMediaTexture.Apply();

            var pre = _resources.preprocess;
            pre.SetInts("ImageSize", _config.InputWidth, _config.InputHeight);
            pre.SetTexture(0, "Input", (Texture)imageMediaTexture);
            pre.SetBuffer(0, "Output", _buffers.preprocess);
            pre.DispatchThreads(0, _config.InputWidth, _config.InputHeight, 1);

          // NNworker invocation
        using (var t = new Tensor(_config.InputShape, _buffers.preprocess))
            _worker.Execute(t);

        // NN output retrieval
        _worker.CopyOutput("scores", _buffers.scores);
        _worker.CopyOutput("boxes", _buffers.boxes);

        // Counter buffer reset
        _buffers.post2.SetCounterValue(0);
        _buffers.counter.SetCounterValue(0);

        // First stage postprocessing: detection data aggregation
        var post1 = _resources.postprocess1;
        post1.SetTexture(0, "Scores", _buffers.scores);
        post1.SetTexture(0, "Boxes", _buffers.boxes);
        post1.SetDimensions("InputSize", _buffers.boxes);
        post1.SetFloat("Threshold", .5f);
        post1.SetBuffer(0, "Output", _buffers.post1);
        post1.SetBuffer(0, "OutputCount", _buffers.counter);
        post1.DispatchThreadPerPixel(0, _buffers.boxes);

        // Second stage postprocessing: overlap removal
        var post2 = _resources.postprocess2;
        post2.SetFloat("Threshold", 0.5f);
        post2.SetBuffer(0, "Input", _buffers.post1);
        post2.SetBuffer(0, "InputCount", _buffers.counter);
        post2.SetBuffer(0, "Output", _buffers.post2);
        post2.Dispatch(0, 1, 1, 1);

        ComputeBuffer.CopyCount(_buffers.post2, _buffers.countRead, 0);
        
        List<DetectedFace> tempFaces = new List<DetectedFace>();
        foreach(var detection in _readCache.Cached){
            Rect tempBbox = new Rect();
            tempBbox.X = (uint)(detection.x2 - detection.x1) / 2;
            tempBbox.Y = (uint)(detection.y2 - detection.y1) / 2;
            tempBbox.Width = (uint)(detection.x2 - detection.x1);
            tempBbox.Height = (uint)(detection.x2 - detection.x1);

            tempFaces.Add(new DetectedFace(){bbox = tempBbox, confidence = detection.score});
        }
        _readCache.Invalidate();
        return new DetectedFaces(){originalImageBitmap = returnFrame.bitmap, Faces = tempFaces.ToArray()};
        }

**Comment by keijiro** [comment] 2022-08-23 01:13
Could you check if Barracuda supports the device? How about other Barracuda samples?

**Comment by matthew-corbett** [comment] 2022-08-23 01:25
I have not tried any other sample, but repos like [this](https://github.com/vlgs/Unity-Barracuda-U2-Net-HoloLens) seems to imply that its possible.

**Comment by matthew-corbett** [comment] 2022-08-23 01:41
It seems that there was a problem in my Texture2D resize from the original bitmap. It now gives me 1 detection with 1 face in view, which is an improvement.  However, the X,Y are miniscule (well below 1, like .000XX).  I'm sure its a scaling problem with the raw detection information, but what part of your code did I mess up?

**Comment by keijiro** [comment] 2022-08-23 02:06
I'm not sure. Debugging without an actual device is almost impossible.

**Comment by matthew-corbett** [comment] 2022-08-23 02:14
Okay. I appreciate your help. I think its because I'm using the X and Y coordinates straight from the model output. They appear to be very small. Your visualizer appears to modify them, which I am not using. Do you know how it is I should modify the raw X,Y coords to fit the image the was used as input to the model?

**Comment by keijiro** [comment] 2022-08-23 02:20
I can't remember it (I haven't touched this project for over a year), but it seems like using normalized UV coordinates. There is nothing special.

https://github.com/keijiro/UltraFaceBarracuda/blob/88bc045cb6ffeff2870988fde7d92463eb49269b/Assets/Visualizer.shader#L34

**Comment by keijiro** [comment] 2022-08-23 02:21
I'm closing this issue now as "not a bug". Please reopen it for further problems.

**Closed as completed by keijiro** 2022-08-23 02:21 UTC
Labels: question
